"""Weekly Digest Tab Module."""

from __future__ import annotations

import streamlit as st
from dashboard import data

from mmi.settings import settings
from mmi.utils.db import connect


def render_digest_tab() -> None:
    """Render the Weekly Digest tab."""
    st.subheader("📰 Weekly Executive Digest & Actionable Market Signals")
    st.caption(
        "Synthesized executive recap of macro environment, active regime shifts, "
        "and quantitative market signals."
    )

    # Executive AI Brief
    brief = data.latest_brief()
    if not brief.empty:
        st.markdown(brief["brief"].iloc[0])
        st.caption(f"Generated by `{brief['engine'].iloc[0]}` · {brief['created_at'].iloc[0]}")
    else:
        st.info("AI Brief unavailable. Run `mmi ai` locally or wait for scheduled refresh.")

    if not settings.snapshot_mode and st.button("🔄 Regenerate brief", use_container_width=True):
        from mmi.ai.narrative import generate_brief

        con = connect()
        try:
            generate_brief(con)
        finally:
            con.close()
        st.cache_data.clear()
        st.rerun()
