"""Weekly Digest Tab Module."""

from __future__ import annotations

import streamlit as st
from dashboard import data
from dashboard.components.utils import verdict_status_message

from mmi.ml.skill_gate import skill_verdict
from mmi.settings import settings
from mmi.utils.db import connect


def render_digest_tab() -> None:
    """Render the Weekly Digest tab."""
    st.subheader("📰 Weekly Executive Digest & Actionable Market Signals")
    st.caption(
        "Synthesized executive recap of macro environment, active regime shifts, "
        "and quantitative market signals."
    )

    # Executive AI Brief
    brief = data.latest_brief()
    if not brief.empty:
        st.markdown(brief["brief"].iloc[0])
        st.caption(f"Generated by `{brief['engine'].iloc[0]}` · {brief['created_at'].iloc[0]}")
    else:
        st.info("AI Brief unavailable. Run `mmi ai` locally or wait for scheduled refresh.")

    # Honest skill-gate status — the escape hatch says plainly when the model is baseline-only.
    metrics = data.model_metrics()
    has_rv_har_spy = (
        not metrics.empty
        and {"model", "symbol"} <= set(metrics.columns)
        and not metrics[(metrics["model"] == "rv_har") & (metrics["symbol"] == "SPY")].empty
    )
    if has_rv_har_spy:
        verdict = skill_verdict(metrics, symbol="SPY")
        label, is_warning = verdict_status_message(verdict)
        if is_warning:
            st.warning(label)
        else:
            st.caption(label)

    if not settings.snapshot_mode and st.button("🔄 Regenerate brief", use_container_width=True):
        from mmi.ai.narrative import generate_brief

        con = connect()
        try:
            generate_brief(con)
        finally:
            con.close()
        st.cache_data.clear()
        st.rerun()
