"""Portfolio Tab Module."""

from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd
import streamlit as st
from dashboard import data
from dashboard.components import charts

from mmi.ai.quant_analyst import PortfolioFacts, generate_quant_brief
from mmi.portfolio.stats import bootstrap_strategy_return_stats
from mmi.settings import settings

_WINDOW_LABELS = {
    "ex_btc_2002": "~2004–present · ex-BTC",
    "ex_btc_2015": "2015–present · ex-BTC (BTC era)",
    "inc_btc_2015": "2015–present · incl. BTC",
}


@st.cache_data(ttl=300, show_spinner=False)
def _return_significance(window_id: str, n_boot: int) -> pd.DataFrame:
    """Paired block-bootstrap on annualised-return differences (full window, not range-filtered).

    Computed at render time from the same mart the pipeline's Sharpe CIs come from, so the return
    gaps get the same honest uncertainty treatment without a schema change.
    """
    pf = data.portfolio_returns(window_id)
    if pf.empty or pf["strategy"].nunique() < 2:
        return pd.DataFrame()
    try:
        _, pairs = bootstrap_strategy_return_stats(
            pf[["strategy", "date", "daily_return"]], n_boot=n_boot
        )
    except ValueError:
        return pd.DataFrame()
    return pairs


@st.cache_data(ttl=300, show_spinner=False)
def _quant_analyst_brief(window_id: str) -> tuple[str, str]:
    """Assemble PortfolioFacts from the marts + the PR-154 return-significance verdicts.

    Deterministic template by default (no LLM key → free/hermetic); the LLM rephrases it only
    when a key is configured (see mmi.ai.quant_analyst).
    """
    pf = data.portfolio_returns(window_id)
    data_date = "" if pf.empty else str(pf["date"].max())[:10]
    stats = data.portfolio_strategy_stats(window_id)
    pairs = data.portfolio_strategy_pairs(window_id)
    ret_pairs = _return_significance(window_id, int(settings.portfolio_n_boot))
    regime = data.portfolio_regime_performance(window_id)
    attr = data.portfolio_attribution(window_id)
    gate = data.portfolio_ml_gate(window_id)
    btc = data.portfolio_btc_effect()

    facts: PortfolioFacts = {
        "as_of": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "data_date": data_date,
        "window_id": window_id,
    }
    if not stats.empty:
        facts["strategies"] = stats.to_dict("records")
    if not pairs.empty:
        facts["sharpe_pairs"] = pairs.to_dict("records")
    if not ret_pairs.empty:
        facts["return_pairs"] = ret_pairs.to_dict("records")
    if not regime.empty:
        facts["regime"] = regime.to_dict("records")
    if not attr.empty:
        facts["attribution"] = attr.to_dict("records")
    if not btc.empty:
        facts["btc_effect"] = btc.to_dict("records")
    if not gate.empty:
        facts["ml_gate"] = {
            "mean_forecast_weight": float(gate["forecast_weight"].mean()),
            "n_dates": int(len(gate)),
        }
    return generate_quant_brief(facts)


def render_portfolio_tab(rng_start: str | None, chart_wrapper) -> None:
    """Render the Portfolio tab."""
    present_windows = data.portfolio_windows()
    if not present_windows:
        st.info(
            "No portfolio backtest yet. "
            "This is expected in the daily-cron partial state: the portfolio backtest runs only "
            "in the full local refresh (`make refresh-full` or `mmi portfolio`). "
            "The committed `data/public/` snapshot will include portfolio results once the "
            "owner's next full run completes."
        )
        return

    window_id = present_windows[0]
    if len(present_windows) > 1:
        window_id = st.radio(
            "Backtest window",
            present_windows,
            format_func=lambda w: _WINDOW_LABELS.get(w, w),
            horizontal=True,
            key="portfolio_window",
        )
        st.caption(
            "⚠️ inc-BTC vs ex-BTC@2002 differs in BOTH universe AND period — use the BTC-impact "
            "section below (the ex/inc 2015 pair) for the clean, same-period BTC comparison. "
            "Volatility regimes are cut within each window, so regime labels aren't comparable "
            "across windows."
        )
    pf = data.portfolio_returns(window_id, rng_start)
    st.caption(
        "Walk-forward backtest: three allocation strategies vs a 60/40 benchmark — same dates, "
        "monthly rebalancing and round-trip costs, so the comparison is like-for-like."
    )
    pairs = data.portfolio_strategy_pairs(window_id)
    if not pairs.empty:
        st.info("📊 " + charts.distinguishability_verdict(pairs))
    quant_text, quant_engine = _quant_analyst_brief(window_id)
    with st.expander("🤖 AI Quant Analyst brief", expanded=False):
        st.markdown(quant_text)
        st.caption(
            f"Generated by `{quant_engine}` · marts: strategy stats, pairs, regime, "
            f"attribution, ML gate, BTC effect"
        )
    chart_wrapper(charts.portfolio_cumulative_chart(pf, height=320))
    if rng_start:
        st.caption("Cumulative return is rebased to 0% at the start of the selected range.")

    with st.expander("📉 Drawdown & rolling Sharpe", expanded=False):
        cda, cdb = st.columns(2)
        with cda:
            chart_wrapper(charts.portfolio_drawdown_chart(pf, height=260))
        with cdb:
            chart_wrapper(charts.portfolio_sharpe_chart(pf, height=260))
        st.dataframe(
            charts.portfolio_summary(pf).style.format(
                {
                    "Total return": "{:+.1%}",
                    "Max drawdown": "{:.1%}",
                    "Ann. vol": "{:.1%}",
                    "Sharpe (252d)": "{:.2f}",
                }
            ),
            width="stretch",
        )

        ret_pairs = _return_significance(window_id, int(settings.portfolio_n_boot))
        if not ret_pairs.empty:
            n_boot = int(ret_pairs["n_boot"].iloc[0])
            ci_pct = int(round(ret_pairs["ci_pct"].iloc[0] * 100))
            st.markdown("**Is the return gap real?**")
            st.dataframe(
                charts.portfolio_return_pairs_table(ret_pairs).style.format(
                    {
                        "Δ Ann. return": "{:+.2%}",
                        "CI low": "{:+.2%}",
                        "CI high": "{:+.2%}",
                        "p-value": "{:.3g}",
                    }
                ),
                width="stretch",
            )
            st.caption(
                f"Paired block-bootstrap ({n_boot:,} resamples, "
                f"{ret_pairs['n_obs'].iloc[0]:,} obs) on annualised geometric return over the full "
                f"{_WINDOW_LABELS.get(window_id, window_id)} window — same resampled dates across "
                f"strategies. Distinguishable = difference CI excludes 0, i.e. "
                f"p < {1 - ci_pct / 100:.2f}."
            )
            st.caption("🧭 " + charts.return_significance_verdict(ret_pairs))

    stats = data.portfolio_strategy_stats(window_id)
    if not stats.empty:
        ci = int(round(stats["ci_pct"].iloc[0] * 100))
        with st.expander(
            f"📊 Risk-adjusted scorecard — Sharpe with {ci}% bootstrap CI", expanded=True
        ):
            sc1, sc2 = st.columns(2)
            with sc1:
                st.dataframe(
                    charts.portfolio_scorecard(stats).style.format("{:.2f}"),
                    width="stretch",
                )
            with sc2:
                if not pairs.empty:
                    st.dataframe(
                        charts.portfolio_pairs_table(pairs).style.format(
                            {"Δ Sharpe": "{:.2f}", "CI low": "{:.2f}", "CI high": "{:.2f}"}
                        ),
                        width="stretch",
                    )
            st.caption(
                f"Stationary block-bootstrap ({stats['n_boot'].iloc[0]:,} resamples, "
                f"{stats['n_obs'].iloc[0]} obs). Distinguishable = Sharpe-diff CI excludes 0."
            )

    attr = data.portfolio_attribution(window_id)
    if not attr.empty:
        with st.expander("📈 Return attribution", expanded=False):
            astrat = st.selectbox(
                "Strategy", sorted(attr["strategy"].unique()), key="attribution_strategy"
            )
            chart_wrapper(charts.attribution_chart(attr, astrat))

    regime = data.portfolio_regime_performance(window_id)
    if not regime.empty:
        with st.expander("🌡️ Performance by market volatility regime", expanded=False):
            chart_wrapper(charts.regime_sharpe_chart(regime))
            st.caption(
                "Market regime = SPY 20-day-vol terciles; stats over each strategy's invested days."
            )

    gate = data.portfolio_ml_gate(window_id, rng_start)
    if not gate.empty:
        with st.expander("🔬 ML experiment — does the forecast add value?", expanded=False):
            st.info("🔬 " + charts.ml_verdict(gate, pairs))
            chart_wrapper(charts.ml_gate_chart(gate))
            st.caption(
                "forecast_weight is the share mvo_ml puts on the ML forecast over the "
                "historical-mean prior, gated point-in-time by the forecast's realised skill. "
                "Pre-registered: expected to stay low."
            )

    btc_effect = data.portfolio_btc_effect()
    if not btc_effect.empty:
        with st.expander(
            "🪙 BTC impact — does adding BTC change risk-adjusted return?", expanded=False
        ):
            st.info("🪙 " + charts.btc_effect_verdict(btc_effect))
            chart_wrapper(charts.btc_effect_chart(btc_effect))
            st.caption(
                "Sharpe(inc-BTC@2015) − Sharpe(ex-BTC@2015): same dates ± BTC, with a "
                "paired block-bootstrap 90% CI. The 60/40 benchmark (never holds BTC) is "
                "exactly zero — a check that the comparison is genuinely paired. "
                "BTC's weekend moves fold into the next trading day, "
                "so its standalone daily vol is understated here."
            )
